alias ll='ls -al'
alias torstr='sudo service tor start'
alias torstp='sudo service tor stop'
alias torst='sudo service tor status'
alias torre='sudo service tor restart'
alias torp='proxychains firefox'
alias basha='sudo nano ~/.bash_aliases'
alias cd..='cd ..'
alias power='cd /home/shimon/packages/powerstager/powerstager'
alias mntv='sudo mount -t cifs -o user=shimon,vers=3.0 //10.100.102.20/Videos /home/shimon/winv'
